Main svc
romilMasnaviev/java-explore-with-me pull request #7
Opened 2024-07-16 19:21 UTC by romilMasnaviev

2024-07-17 12:12 UTC, ErkinKasymaliev requested changes
привет, оставил комменты, и еще общие замечания:
1) Внедряйте зависимости через @RequiredArgsConstructor
2) используйте Pageable
3) также не увидел чтобы вы использовали @Transactional в сервисах

2024-07-17 12:12 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/controller/category/AdminCategoryController.java
> +@AllArgsConstructor
@RequiredArgsConstructor

2024-07-17 12:12 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/controller/category/AdminCategoryController.java
> +    private CategoryService service;
private final

2024-07-17 12:12 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/controller/category/AdminCategoryController.java
> +    @PostMapping()
@PostMapping

2024-07-17 12:12 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/controller/category/PublicCategoryController.java
> +    public CategoryService service;
в контроллере выше оставил комменты, лучше инжектите след образом:
@RequiredArgsConstructor над классом
private final к полям которые должны быть внедрены

2024-07-17 12:12 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/controller/category/PublicCategoryController.java
> +    public CategoryDto getCategory(@PathVariable(name = "catId") @Min(value = 0) Integer catId) {
зачем здесь @Min, это же айдишник

2024-07-17 12:12 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/controller/category/AdminCategoryController.java
> +    public ResponseEntity<HttpStatus> deleteCategory(@PathVariable @Min(value = 0) Integer catId) {
зачем здесь @min, это же айдишник

2024-07-17 12:12 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/controller/category/AdminCategoryController.java
> +    public CategoryDto updateCategory(@PathVariable @Min(value = 0) Integer catId,
зачем здесь @min, это же айдишник

2024-07-17 12:12 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/controller/compilation/AdminCompilationController.java
> +    public ResponseEntity<HttpStatus> deleteCompilation(@PathVariable(name = "compId") @Min(value = 0) Integer compId) {
ну вы поняли)

2024-07-17 12:12 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/controller/category/PublicCategoryController.java
> +    @GetMapping()
скобочки не нужны, поправьте в других местах тоже

2024-07-17 12:12 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/dao/CategoryRepository.java
> +    List<Category> findAllCategories(@Param("offset") int offset, @Param("limit") int limit);
а почему бы здесь PageAble не использовать и без nativeQuery

2024-07-17 12:12 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/dao/CategoryRepository.java
> +@Service
@Repository
поправьте во всем пакете

2024-07-17 12:12 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/dao/EventRepository.java
> +    List<Event> getUserEvents(@Param("offset") Integer offset, @Param("limit") Integer limit, @Param("id") Integer userId);
а почему бы здесь PageAble не использовать и без nativeQuery

2024-07-17 12:12 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/dao/UserRepository.java
> +@Service
Repository

2024-07-17 12:12 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/service/EventService.java
> +    void saveEndpointHit(HttpServletRequest request) {
private или public?

2024-07-17 12:48 UTC, romilMasnaviev commented on main-service/src/main/java/ru/practicum/dao/CategoryRepository.java
> +    List<Category> findAllCategories(@Param("offset") int offset, @Param("limit") int limit);
По документации было, что offset - количество элементов для пропуска, а limit - всего количество элементов.  
Если создавать PageAble - то from - номер страницы, с которой начинать, а size: размер страницы ( количество записей). Поэтому решил сделать через nativeQuery и использовать limit и offset, т.к в jpql нет таких понятий.

2024-07-17 12:48 UTC, romilMasnaviev commented on main-service/src/main/java/ru/practicum/dao/CategoryRepository.java
> +    List<Category> findAllCategories(@Param("offset") int offset, @Param("limit") int limit);
Исправил на pageAble, тесты проходят

2024-07-18 11:45 UTC, ErkinKasymaliev approved these changes
привет, работа принята!
@Transactional нужен для методов где происходит запись в бд, там где только чтение аннотация не нужна.
к следующей работе поправьте

2024-07-18 12:45 UTC, merged