Feature comments
romilMasnaviev/java-explore-with-me pull request #8
Opened 2024-07-19 17:42 UTC by romilMasnaviev

2024-07-20 12:01 UTC, ErkinKasymaliev requested changes
привет, хорошая работа!
Оставил комменты, надо поправить не только там где их оставил, а везде по коду

2024-07-20 12:01 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/controller/category/PublicCategoryController.java
> +    public CategoryDto getCategoryPublic(@PathVariable(name = "catId") Integer catId) {
(name = "catId") это необязательно прописывать если название переменной сходится с тем что в фигурных скобках

2024-07-20 12:01 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/service/category/AdminCategoryService.java
> +    ResponseEntity<CategoryDto> createCategoryByAdmin(NewCategoryDto newCategory);
нее, в responseEntity оборачивайте в контроллере, в сервисах возвращайте dto

2024-07-20 12:01 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/service/category/CategoryService.java
> +    public ResponseEntity<CategoryDto> createCategoryByAdmin(NewCategoryDto newCategory) {
обязательно добавляйте @Override для имплементированных методов

2024-07-20 12:05 UTC, romilMasnaviev commented on main-service/src/main/java/ru/practicum/controller/category/PublicCategoryController.java
> +    public CategoryDto getCategoryPublic(@PathVariable(name = "catId") Integer catId) {
Да, знаю. Думал лучше будет если прописать ( чтобы если кто-то изменит - будет работать)

2024-07-21 06:14 UTC, ErkinKasymaliev approved these changes
привет, работа принята!
Поздравляю с успешным окончанием курса! Удачи вам!

2024-07-29 14:39 UTC, merged